CREATE TABLE phones
             (
                          usuario_id  INTEGER,
                          id          BIGINT generated BY DEFAULT AS IDENTITY,
                          city_code   varchar(255),
                          contry_code varchar(255),
                                      number varchar(255),
                          PRIMARY KEY (id)
             );

CREATECREATE TABLE usuarios
             (
                          id        INTEGER generated BY DEFAULT AS IDENTITY,
                          is_active boolean,
                          created timestamp(6),
                          last_login timestamp(6),
                          modified timestamp(6),
                          email    varchar(90) UNIQUE,
                          NAME     varchar(120),
                          password varchar(255),ALTER TABLEIF EXISTS phones ADD CONSTRAINT fkbihfv0y4tlyjxvy8vstv2jkgo FOREIGN KEY (usuario_id) REFERENCES usuarios;
